version: "3.9"
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: password
  web:
    # env_file: .env
    restart: "always"
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=$$RAILS_ENV bundle exec rails db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0' -e $$RAILS_ENV"
    volumes:
      - .:/v-for-vehicle
    ports:
      - "3000:3000"
    environment:
      POSTGRESQL_HOST: ${POSTGRESQL_HOST}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      RAILS_ENV: ${RAILS_ENV}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
    # depends_on:
    #   - db
    # db already on local

  elasticsearch:
    image: elasticsearch:2.0
    command: elasticsearch -Des.network.host=0.0.0.0

  logstash:
    image: logstash:2.0
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "12201:12201/udp"
    volumes:
      - "./logstash:/etc/logstash/conf.d"
    links:
      - elasticsearch

  kibana:
    image: kibana:4.2
    links:
      - elasticsearch
    ports:
      - "5601:5601"


